proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=ask_cache:10m max_size=100m inactive=10m use_temp_path=off;

upstream django {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name localhost;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    location ^~ /uploads/ {
        expires 7d;
        add_header Cache-Control "public";
        alias /home/hpxhq/projects/2026-VK-EDU-Web-11-Kolesnikova-D-hw-3/uploads/;
    }
    
    location ^~ /static/ {
        alias /home/hpxhq/projects/2026-VK-EDU-Web-11-Kolesnikova-D-hw-3/staticfiles/;
        expires 7d;
        add_header Cache-Control "public";
    }
    location ^~ /media/ {
        alias /home/hpxhq/projects/2026-VK-EDU-Web-11-Kolesnikova-D-hw-3/media/;
        expires 7d;
        add_header Cache-Control "public";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|html)$ {
        root /home/hpxhq/projects/2026-VK-EDU-Web-11-Kolesnikova-D-hw-3/static;
    }
    location / {
    	proxy_pass http://django;
    	proxy_cache ask_cache;
    	proxy_cache_valid 200 1m;
    	add_header X-Proxy-Cache $upstream_cache_status;
    	proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
    }
}
